ALTER TABLE `Collaborator`
ADD COLUMN `shortName` VARCHAR(120) NULL,
ADD COLUMN `birthDate` DATETIME(3) NULL,
ADD COLUMN `gender` VARCHAR(30) NULL,
ADD COLUMN `documentExtended` BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN `residenceArea` VARCHAR(120) NULL,
ADD COLUMN `insurancePolicy` VARCHAR(120) NULL,
ADD COLUMN `allergies` TEXT NULL,
ADD COLUMN `greenReceipt` VARCHAR(20) NULL,
ADD COLUMN `availability` TEXT NULL,
ADD COLUMN `photo` LONGTEXT NULL;
