ALTER TABLE "Client" ADD COLUMN "minimumHours" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "Event" ADD COLUMN "realHours" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "Event" ADD COLUMN "minimumHoursSnapshot" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "EventAssignment" ADD COLUMN "clientRealHours" DECIMAL NOT NULL DEFAULT 0;
