ALTER TABLE `Collaborator` ADD COLUMN `hasOwnCar` BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE `Budget` ADD COLUMN `travelCars` LONGTEXT NULL;
ALTER TABLE `Event` ADD COLUMN `travelCars` LONGTEXT NULL;
ALTER TABLE `EventAssignment` ADD COLUMN `isDriver` BOOLEAN NOT NULL DEFAULT false;
